### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by allanderek**
I've revamped the testing apparatus. The headline news is that there are two most useful test commands:
python manage.py test_casper
and
python manage.py test_units
Both perform (by default) coverage analysis.

You till have the test_module and test_package commands which can also perform coverage analysis but it is off by default (because it's probably not that interesting if you are not running all the tests).

Unfortunately you can only really interpret the coverage results for either the unit tests or the casper tests, they are not merged. I think I could get them merged with a bit of work.

Another great point is that now, if you're running tests against a live server, coverage analysis is still an option (obviously otherwise it wouldn't work for the casper tests), *AND* the server is automatically shut down, you don't even have to worry about that in your tests (so you'll note that in app/coffee/tests/browser.coffee we no longer have to make a post request to 'localhost:5000/shutdown'.
This also means that if we write more Selenium tests they can have coverage analysis done on the server code *and* we don't need to shutdown the server manually either.

Try running:
python manage.py test_casper
and then looking at the htmlcov/index.html
and you can see some nice coverage analysis showing which lines were hit and which weren't. In particular look at app/main and app/go (arguably for test_casper we should not include app/tests/ in the source, but this is configured in the .coveragerc file so I'm loathe to override it with a --source argument).

More controversially, I've removed the 'app/browser_tests' directory. Partly this was a bit of hodge-podge of out-of-date code. More importantly these tests did not seem to do anything worthwhile or am I missing something. Previous it was app/browser_tests/test_phantom.py that ran the casper tests but that is done directly from manage.py so it is not necessary now.

Overall I think this is ten-times cleaner and we at least have some coverage analysis working properly.

Oh and all the tests are passing on my machine :)

### CODE REVIEW

**Comment by karlorg** [comment]
Cool, I was not looking forward to removing Persona, glad that's done.

Is there no way any more to run a single Casper test?  That could make the client-side workflow pretty nasty if we have to run the entire Casper test suite every time we want to test a change :/

**Comment by allanderek** [comment]
Okay, let me look into this, I'll restore it no problem.

**Comment by karlorg** [comment]
should just be a matter of adding `--single=<test name>` to the arguments to the casper runner

**Comment by allanderek** [comment]
Yes, I re-enabled doing 'python manage.py test_casper --name ...' it was pretty easy.
Still not quite satisfied because I would really like to combine the coverage analysis results from the casper and non-casper tests.

**Pull request merged**
