### PR TITLE
Last played indicator and header describing who the players are

### PR DESCRIPTION
**Pull request by allanderek**
A little bit fiddly the header, and still the whole thing looks quite ugly, but again, it is mostly only a matter of changing the CSS. I'm trying to keep it that way so that eventually we can make the thing look somewhat prettier without changing any functionality.

### CODE REVIEW

**Comment by karlorg** [comment]
On 26/06/2015 15:27, allanderek wrote:

>   * Fixed merge conflicts which arose from concurrent update to both
>     displaying prisoners and displaying the last stone placed.

Oops, forgot to 'git fetch allan' before merging into master.  Next time.

**Comment by allanderek** [comment]
On 26 June 2015 at 15:29, karlorg <notifications@github.com> wrote:

> On 26/06/2015 15:27, allanderek wrote:
>
> > * Fixed merge conflicts which arose from concurrent update to both
> > displaying prisoners and displaying the last stone placed.
>
> Oops, forgot to 'git fetch allan' before merging into master. Next time.
>
>
No no, that was my fault if anyone's. I had not pushed it to github (but
arguably I was not finished working so was not really ready to publish). In
either case, that's fine, that's what the source control is there for ;)

**Comment by karlorg** [comment]
On 26/06/2015 15:31, allanderek wrote:

> No no, that was my fault if anyone's. I had not pushed it to github (but
> arguably I was not finished working so was not really ready to publish). In
> either case, that's fine, that's what the source control is there for ;)

Yeah so far I've found merging conflicts quite manageable.

(could get interesting the first time we have two simultaneous db 
changes; someone will have to check both migrations and make one follow 
on from the other properly, as they'll initially both be based on the 
same prior migration)

**Comment by allanderek** [comment]
On 26 June 2015 at 15:34, karlorg <notifications@github.com> wrote:

> On 26/06/2015 15:31, allanderek wrote:
>
>
> Yeah so far I've found merging conflicts quite manageable.
>
> (could get interesting the first time we have two simultaneous db
> changes; someone will have to check both migrations and make one follow
> on from the other properly, as they'll initially both be based on the
> same prior migration)
>
>
Stop it, I'll have nightmares.

**Comment by karlorg** [comment]
On 26/06/2015 15:36, allanderek wrote:

>  > (could get interesting the first time we have two simultaneous db
>  > changes; someone will have to check both migrations and make one follow
>  > on from the other properly, as they'll initially both be based on the
>  > same prior migration)

> Stop it, I'll have nightmares.

hehe, I think it'll actually be easy enough.  As long as we notice 
what's happened.

**Pull request merged**
