### PR TITLE
Add pytest as an option

### PR DESCRIPTION
**Pull request by allanderek**
So just as the commit messages say, I got a bit dissatisfied with casper and decided to create a pytest/selenium browser test.

Note that this includes an update to the requirements so you will have to re-run:

    $ pip install -r requirements.txt

### CODE REVIEW

**Comment by karlorg** [comment]
argh I don't like this idea at all :(  It was such a relief when we finally got rid of Selenium; no more having my screen taken over by its popup windows, no more tests flaking out when I update Firefox because Selenium was relying on some behaviour in the old version.  (And I kind of like the CasperJS API too, mostly because it's Javascripty I guess, and I admit that's probably a matter of taste.)

If we're going to have to put explicit waits in Selenium tests anyway, why not just convert the Casper tests as we find more points where they tend to break?  (That is, if we're confident that will fix it, which I'm still not sure of.)  If we were sure Selenium would be more stable it might be worth switching over again, but I seem to remember it being pretty flaky before.

**Comment by allanderek** [comment]
I think your experience was particularly with the Firefox web driver,
instead I'm using the phantomJS web driver, it feels many times more
reliable than casperjs.

Give it a chance. Try doing:

    git  checkout -b pytest-try
    git pull allanderek master
    pip install -r requirements.txt
    python manage.py test_pytest

Admittedly not really a comparable test because it currently has only two
pretty trivial tests. But you'll note the lack of annoying pop up windows,
and random failures.

**Comment by allanderek** [comment]
I should have said this is based on other projects in which I have found
selenium to be more reliable.

**Comment by karlorg** [comment]
On 28/04/2016 16:35, allanderek wrote:
> I think your experience was particularly with the Firefox web driver,
> instead I'm using the phantomJS web driver, it feels many times more
> reliable than casperjs.

Oh OK that might work out then.  I have some changes going on just now, 
once I'm done I'll take a look.

**Pull request merged**
