### PR TITLE
Added in game chatting.

### PR DESCRIPTION
**Pull request by allanderek**
It is pretty basic at the moment, and I can't say it looks terribly nice. I think ultimately I would at least like for comments to be highlighted as to who made which comment. I might even implement it such that the players decide whether to open the chat up to non-players. But I'm not terribly keen on building a comprehensive chatting platform, because I just don't think it's required. I think the chat during the game is pretty minimal. So I'm not even intending to implement, say, simple markdown etc. These kind of features will come on an as-requested basis.

### CODE REVIEW

**Comment by allanderek** [comment]
Added a further commit which tidies up setup and adds a script for deployment to pythonanywhere. One thing I had not realised when I advocated for not storing the compiled Javascript files in the repository was that on python anywhere we would need to install coffee-script to be able to generate the static JS files ourselves. But I've done that now so it is fine.

**Comment by allanderek** [comment]
Another commit which adds the storing of the logged in email when someone makes a comment on a game and uses that when displaying the comments of a game.

**Comment by karlorg** [comment]
On 24.06.2015 16:11, allanderek wrote:
> Another commit which adds the storing of the logged in email when
> someone makes a comment on a game and uses that when displaying the
> comments of a game.

ooh, were you able to upgrade the server without wiping the db?

**Comment by allanderek** [comment]
Yes. But as you can see one of my earlier comments is attributed to no one, rather than to me. But that could be done with the migration if I had a real mind to do so. But I didn't have to wipe any games or anything.

**Pull request merged**
